# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: ARC Runner Basic Test
on:
  workflow_dispatch:

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-arc:
    name: "Basic GPU Test for ARC Runner Validation"
    runs-on: linux-mi300-1gpu-ossci-gitops
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@v4

      - name: "Test rocm commands"
        run: |
          rocm-smi
          rocminfo
